//
//  CreateDeleteDirectoryTools.swift
//  Sage
//

import Foundation

nonisolated struct CreateDirectoryTool: AgentTool {
    let definition = ToolDefinition(
        name: "create_directory",
        description: """
            Create a directory (and any missing parent directories) inside the active sandbox \
            (home ~/ or the focused project root). Safe to call if the directory already exists.
            """,
        parameters: .schemaObject(
            properties: [
                "path": .stringProperty("Directory path to create"),
            ],
            required: ["path"]
        )
    )

    private struct Args: Decodable { let path: String }

    func call(argumentsJSON: String) throws -> String {
        let args = try decodeToolArgs(argumentsJSON, as: Args.self)
        let url = try PathGuard.resolveAllowed(args.path)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return "[OK] Created \(PathGuard.displayPath(url.path))"
    }
}

nonisolated struct DeleteFileTool: AgentTool {
    let definition = ToolDefinition(
        name: "delete_file",
        description: """
            Delete a file or an empty directory under ~/. \
            Non-empty directories cannot be deleted — remove their contents first. \
            This operation is irreversible.
            """,
        parameters: .schemaObject(
            properties: [
                "path": .stringProperty("Path to the file or empty directory to delete (must exist)"),
            ],
            required: ["path"]
        )
    )

    private struct Args: Decodable { let path: String }

    func call(argumentsJSON: String) throws -> String {
        let args = try decodeToolArgs(argumentsJSON, as: Args.self)
        let url = try PathGuard.resolveAllowed(args.path)
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw ToolError.operationFailed(
                "File does not exist: \(args.path). Use list_directory to verify the path."
            )
        }
        // Safety: refuse to delete non-empty directories
        var isDir: ObjCBool = false
        FileManager.default.fileExists(atPath: url.path, isDirectory: &isDir)
        if isDir.boolValue {
            // Exclude .DS_Store from emptiness check — it's auto-generated by Finder
            guard let contents = try? FileManager.default.contentsOfDirectory(atPath: url.path) else {
                throw ToolError.operationFailed(
                    "Cannot read directory contents: \(args.path). Check permissions."
                )
            }
            let meaningful = contents.filter { $0 != ".DS_Store" }
            if !meaningful.isEmpty {
                throw ToolError.operationFailed(
                    "Directory is not empty (\(meaningful.count) items). Remove contents first."
                )
            }
        }
        try FileManager.default.removeItem(at: url)
        return "[OK] Deleted \(PathGuard.displayPath(url.path))"
    }
}
